# Generated by Django 4.2 on 2024-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='stereo_mapping',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
