# Generated by Django 4.2 on 2024-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_vision_stereo_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='stereo_mapping',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('sidebyside', 'Side By Side'), ('topbottom', 'Top Bottom')], default='normal', max_length=100, null=True),
        ),
    ]
