# Generated by Django 4.0.4 on 2024-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vision',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
