# Generated by Django 4.2 on 2024-06-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_vision_stereo_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vision'),
        ),
    ]
