# Generated by Django 4.2 on 2024-06-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_comment_parent_comment_alter_comment_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('16:9', '16:9'), ('4:3', '4:3'), ('VR180', 'VR180'), ('VR360', 'VR360')], default='', max_length=6, null=True),
        ),
    ]
