# Generated by Django 4.2 on 2024-06-30 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_signincoderequest_user_and_more'),
        ('videos', '0005_alter_vision_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vision',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vision',
            name='private_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='likes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='vision',
            name='views',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
