# Generated by Django 4.2 on 2024-06-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_vision_is_highlight_vision_is_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='videos.vision'),
        ),
    ]
