# Generated by Django 4.2 on 2024-06-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_interests_spectator_interests'),
        ('videos', '0007_alter_comment_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vision', to='users.creator'),
        ),
    ]
