# Generated by Django 4.2 on 2024-07-25 19:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_creator_search_vector_and_more'),
        ('videos', '0008_alter_vision_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddIndex(
            model_name='vision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='videos_visi_search__68d185_gin'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='users.user'),
        ),
    ]
