# Generated by Django 4.2 on 2024-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, to='videos.comment'),
        ),
        migrations.AddField(
            model_name='spectator',
            name='liked_visions',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='videos.vision'),
        ),
        migrations.AddField(
            model_name='spectator',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='users.creator'),
        ),
        migrations.AddField(
            model_name='spectator',
            name='watch_history',
            field=models.ManyToManyField(blank=True, related_name='watch_history_by', to='videos.vision'),
        ),
        migrations.AddField(
            model_name='spectator',
            name='watch_later',
            field=models.ManyToManyField(blank=True, related_name='watch_later_by', to='videos.vision'),
        ),
    ]
