# Generated by Django 4.2 on 2024-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='bio',
        ),
        migrations.AddField(
            model_name='creator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
