# Generated by Django 4.2 on 2024-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_creator_bio_creator_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
