# Generated by Django 4.2 on 2024-06-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_signincoderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signincoderequest',
            name='updated_at',
        ),
    ]
