# Generated by Django 4.2 on 2024-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_signincoderequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture_url',
            field=models.CharField(default='https://res.cloudinary.com/pov/image/upload/v1667553173/defaultPic_s89yno.png', max_length=400),
        ),
    ]
