# Generated by Django 4.2 on 2024-06-30 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_cover_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signincoderequest',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='spectator',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, db_index=True, to='users.creator'),
        ),
    ]
