# Generated by Django 4.2 on 2024-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_date_joined_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='spectator',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.interest'),
        ),
    ]
