# Generated by Django 4.2 on 2024-07-25 19:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_sign_in_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='users_creat_search__6a58cd_gin'),
        ),
    ]
