# Generated by Django 4.2 on 2024-06-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.creator')),
                ('remind_me_list', models.ManyToManyField(blank=True, to='users.spectator')),
                ('vision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.vision')),
            ],
        ),
    ]
