# Generated by Django 4.2 on 2024-07-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
